name: Prueba_GHA

on:
  pull_request:
  push:
    paths:
      - 'tareas/Ibarra_Ara/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker Image
      run: |
        docker build -t gitact_hw tareas/Ibarra_Ara
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.GITACT_HW_USER }} -p ${{ secrets.GITACT_HW_KEY }}
    - name: Tag Docker Image
      run: docker tag gitact_hw ${{ secrets.GITACT_HW_USER }}/gitact_hw:latest
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.GITACT_HW_USER }}/gitact_hw:latest
    - name: Run Docker Container
      run: |
        docker run ${{ secrets.GITACT_HW_USER }}/gitact_hw > output.log
    - name: Print Docker Output
      run: |
        cat output.log

